{% set name = "qt-material" %}
{% set version = "2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6e2b159f2b336e45d8bb972637cf7ba4f5058ce2799ff3e73bd23bf636782ea3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jinja2
    - python >=3.7

test:
  imports:
    - qt_material
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/UN-GCPDS/qt-material
  summary: Material inspired stylesheet for PySide2, PySide6, PyQt5 and PyQt6.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
